### PR TITLE
Add a minimal travis configuration

### LINKED ISSUE #7: Propose a CI implementation and tool
**Is your feature request related to a problem? Please describe.**
CI is not implemented on this project. It should be.

**Describe the solution you'd like**
We are open to trying new tools. Travis ? CircleCI ? We need a proposal.

### PR DESCRIPTION
**Pull request by lcor-io**
# Fixes #7 
**Summary:**

Add a minimal travis setup for the project

**Changes:**

- Add a .travis.yml file to describe the CI. Currently it's playing tests on each branch, at each commits
- The result of the build is accessible on [travis](https://travis-ci.com/reacli/cli)

**Todos:**

- Add tests
- Restrict merges on develop and master if builds are KO

### CODE REVIEW

**Comment by lcor-io** [comment]
The Sonar analysis is accessible from the [SonarCloud ](https://sonarcloud.io/dashboard?id=reacli_cli) page

**Comment by lcor-io** [comment]
And yes, I had some issues fixing the CI...

**Review by gdarchen — APPROVED** [review]
Seems good to me 😊 
We will have to look at our SonarCloud page to see if metrics come up when we will have some tests written.

**Comment by tanohzana** [comment]
It looks like some checks failed... What do we do with that ?

**Comment by lcor-io** [comment]
My guess is that it's some older builds still displaying. I looked in the _check_ panel and they do not appear here. They also don't exist in the latest travis build log

**Pull request merged**
