### PR TITLE
Add an option to choose the file extension ('.js' or '.jsx') when creating components

### LINKED ISSUE #47: Add an option to choose the extension of component files
**Is your feature request related to a problem? Please describe.**
Today, generated components are in `.jsx` files. Some users might want the generated components to be in `.js` files. We should then add an option enabling that.

This option should also be configurable in the `.reacli` file.

**Describe the solution you'd like**
Maybe we could use this option like `--js` or `--extension=js`.

In the `.reacli` file, this option could be either:

```json
{
  "js": true,
}
```
or 
```json
{
  "extension": "js",
}
```
depending on the choice made on the "inline" version of the option (`--js`, `--extension=js` or other).

**Additional context**
Do not forget to update the docs when solving this issue 😄

### PR DESCRIPTION
**Pull request by gdarchen**
# Fixes #47 

**Summary:**

I added an argument `--extension [value]` to choose the file extension when creating a new *component*. 

`[value]` can take the following values:
- `js`
- `jsx`

When not used, the default extension that is used is `.jsx`.

You can see an example of its usage here:
image

I also updated the interactive CLI to make it ask the user the file extension he wants to use:
image

Finally, I also enabled the fact choosing the file extension directly from the `.reacli` file, like:
```json
{
  "extension": "js",
}
```

**Changes:**

* `bin/reacli.js`: add the `--extension` option and validate its value before potentially using it
* `lib/core.js`: log the extension used if not using the default one (`jsx`)
* `lib/interactiveCLI.js`: add the question to get the file extension and add the answer to the `options` object
* `lib/utils/files.js`: use the selected extension or the default one
* `lib/utils/validators.js`: add a method to validate the extension and check its value is either `js` or `jsx`

**Dependencies:**

[#43](https://github.com/reacli/cli/pull/43)

**Instructions:**

Try creating a component using the `--extension` with both values (`js` and `jsx`), and check the file extensions of the generated component matches. Also try creating a `.reacli` file and setting the `"extension"` option as described above. 

Redo the same checks with the interactiveCLI 😊

### CODE REVIEW

**Comment by tanohzana** [comment]
- [x] feature is working
 - [ ] no breaking change was caused
 - [x] code is clean
 - [ ] new tests pass

**Review by tanohzana — APPROVED** [review]
SGTM 😁 Let's merge #56 first so you can rebase `develop` and make sure no test is broken. Then, would you mind writing the tests about this feature ? It might be rough at first to get familiar with the way the tests are written, but I'm sure it's a good exercise for the future. If you have other things to do, I can do it, it will take me 5 mins.

**Comment by gdarchen** [comment]
I'm quite busy right now. If you think this can be done during the week, I can do it. If you think it has be done fast, then do it and I will have a look at it 😉

**Comment by tanohzana** [comment]
Alright, I'll do it once #56 is merged 😉

**Comment by gdarchen** [comment]
> Alright, I'll do it once #56 is merged 😉

I'm on it 😉

**Comment by gdarchen** [comment]
I have written some tests for this new feature, please have a look at it (https://github.com/reacli/cli/pull/51/commits/6b4fb767ed332324fb158d90f4d44360a08962a7). I also refactored a bit the interactive CLI to make it ask for the file extension even if we are creating a hook.

In https://github.com/reacli/cli/pull/51/commits/0359708a0c656f18160106d6ab74bee691e1b938, I just solved a conflict.

**Pull request merged**
