### PR TITLE
Feat/add commander

### PR DESCRIPTION
**Pull request by lcor-io**
# Issue #14 

**Summary:**

> Add commander to manage the cli parameters

**Changes:**

> No changes should be visible while using the cli, as it's simply some refactoring

**Dependencies:**

> If this pull request is dependent to one or multiple other ones, list them here

* commander
* pkginfo

**Context**

> Commander will collide with the previous pull request concerning redux, there will be conflict issues

### CODE REVIEW

**Review by gdarchen — CHANGES_REQUESTED** [review]
It seems good to me but the whole indentation has changed here. Could you try adding an ESLint rule so as to fix it and have in your changes only the functions in which you changed things ? 😊

**Comment by lcor-io** [comment]
Yeah, saw it after I created the PR, my bad I will fix this with an Eslint rule.

**Comment by gdarchen** [comment]
By the way, there are some conflicts to be solved before merging it 😉

**Comment by anatol-grabowski** [comment]
I thought the indent change was international lol Was glad you guys gave up on tabs (8 spaces?) cause that's rediculous))

**Comment by tanohzana** [comment]
@grabantot we still use tabs but we set them to 2 spaces 🙂

**Review by gdarchen — APPROVED** [review]

**Pull request merged**
